#!/bin/bash


IMAGE=db2-aufs

set -e

instance_bind_mount_root=$1
if [[ -z $instance_bind_mount_root ]] || \
	[[ ! -d $instance_bind_mount_root ]] || \
	[[ `ls -A $instance_bind_mount_root` ]]; then
	echo "error: must provide an empty directory for storing bind-mounted db2 instance directory." 2>&1
	exit 1
fi
# docker -v wants an abspath
instance_bind_mount_root=$(readlink -f $instance_bind_mount_root)

# Build the Dockerfile.  This will do everything up to creating and populating the instance
docker build -t $IMAGE:$revision .

# Start a container, running the install script, and then commit
docker run --privileged -v $instance_bind_mount_root:/db -t $IMAGE:$revision ./install.sh
containerid=$(sudo docker ps -l | grep $IMAGE:$revision | awk '{print $1}')
docker stop $containerid
docker commit $containerid $IMAGE:$revision

